### ISSUE TITLE
[Feature Request]: Add ML Snippets Folder for Reusable Data Preprocessing Steps

### ISSUE THREAD

**Issue by 770navyasharma** [UTSAVS26/PySnippets#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to propose adding a new folder titled ML_Snippets to the repository. This folder will contain a Jupyter Notebook that showcases the most reusable data preprocessing steps commonly used in machine learning projects. The aim is to provide a quick reference for users looking for efficient ways to prepare their data for modeling.

I would like to have this issue assigned to me as part of the Hacktoberfest and GSSoC initiatives, preferably at Level 2 or 3.

Thank you for considering this addition! I look forward to your feedback.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by UTSAVS26** [comment]
Thank you for your proposal to add the **ML_Snippets** folder to the PySnippets repository. However, to maintain consistency with the main idea of deploying PySnippets as a package, we recommend writing the reusable data preprocessing steps as Python files (.py) instead of a Jupyter Notebook. 

This approach will allow users to easily import the snippets directly into their projects and integrate them seamlessly into their workflows. If you could revise your submission accordingly, that would be great!

We look forward to your contribution!

**Comment by 770navyasharma** [comment]
Suree
